//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub file_id: i32,
    pub file_name: String,
    #[sea_orm(unique)]
    pub full_path: String,
    pub file_size: i32,
    pub parent_dir_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "crate::Dirs",
        from = "Column::ParentDirId",
        to = "crate::DirsColumn::DirId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Dirs,
}

impl Related<crate::Dirs> for Entity {
    fn to() -> RelationDef {
        Relation::Dirs.def()
    }
}

pub struct SelfReferencingLink;

impl Linked for SelfReferencingLink {
    type FromEntity = Entity;

    type ToEntity = Entity;

    fn link(&self) -> Vec<RelationDef> {
        vec![Relation::Dirs.def()]
    }
}

impl ActiveModelBehavior for ActiveModel {}
