//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::files::{
    ActiveModel as FilesActiveModel, Column as FilesColumn, Entity as Files, Model as FilesModel,
    PrimaryKey as FilesPrimaryKey, Relation as FilesRelation,
};
