//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::dirs::{
    ActiveModel as DirsActiveModel, Column as DirsColumn, Entity as Dirs, Model as DirsModel,
    PrimaryKey as DirsPrimaryKey, Relation as DirsRelation,
};
